version: '3'

services:
  app:
    image: weseek/growi:7
    links:
      - mongo:mongo
      - elasticsearch:elasticsearch
    depends_on:
        mongo:
          condition: service_healthy
        elasticsearch:
          condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/growi
      ELASTICSEARCH_URI: http://elasticsearch:9200/growi
      PASSWORD_SEED: ${PASSWORD_SEED}
      FILE_UPLOAD: local     # activate this line if you use local storage of server rather than AWS

    entrypoint: "/docker-entrypoint.sh"
    command: ["npm run migrate && node -r dotenv-flow/config --expose_gc dist/server/app.js"]

    restart: unless-stopped
    volumes:
      - growi_data:/data

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_configdb:/data/configdb
      - mongo_db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 6

  elasticsearch:
    build:
      context: ./elasticsearch/v8
      dockerfile: ./Dockerfile
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"  # increase amount if you have enough memory
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true # CVE-2021-44228 mitigation for Elasticsearch <= 6.8.20/7.16.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/v8/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  growi_data:
    driver_opts:
      type: nfs
      o: "addr=10.24.0.41,hard,rsize=1048576,wsize=1048576,nfsvers=4"
      device: ":/DockerVolumes/growi_data"
  mongo_configdb:
  mongo_db:
  es_data:
